apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jellyfin
  name: jellyfin-pvc-media
  namespace: jellyfin-ns
spec:
  storageClassName: ""
  volumeName: jellyfin-pv-media
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Gi