apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-media
  labels:
    app: jellyfin
spec:
  storageClassName: ""
  claimRef:
    name: jellyfin-pvc-media
    namespace: jellyfin-ns
  capacity:
    storage: 3Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/jellyfin/media"