apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-pv-downloads
  labels:
    app: deluge
spec:
  storageClassName: ""
  claimRef:
    name: deluge-pvc-downloads
    namespace: deluge-ns  
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/deluge/downloads"