apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: deluge
  name: deluge-pvc-cache
  namespace: deluge-ns
spec:
  storageClassName: ""
  volumeName: deluge-pv-cache
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi