apiVersion: v1
kind: Service
metadata:
  labels:
    app: deluge
  name: deluge-svc
  namespace: deluge-ns
spec:
  type: LoadBalancer      
  ports:
    - name: "8112"
      port: 8112
      targetPort: 8112
  selector:
    app: deluge