apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge-igr
  namespace: deluge-ns
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - secretName: delugetest-iacono-io-tls
      hosts:
        - delugetest.iacono.io
  ingressClassName: traefik
  rules:
  - host: delugetest.iacono.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deluge-svc
            port:
              number: 8112