apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
  name: deluge-dpl
  namespace: deluge-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 1.1.1.2
        - 1.0.0.2
        options:
        - name: ndots
          value: "5"
        searches:
        - deluge.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      containers:
        - env:
            - name: DELUGE_PublishedServerUrl
              value: http://delugetest.iacono.io
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/deluge:latest
          name: deluge
          ports:
            - containerPort: 8096
          volumeMounts:
            - mountPath: /config
              name: deluge-config
            - mountPath: /downloads
              name: deluge-downloads
            - mountPath: /completed
              name: deluge-completed
      restartPolicy: Always
      volumes:
        - name: deluge-config
          persistentVolumeClaim:
            claimName: deluge-pvc-config
        - name: deluge-downloads
          persistentVolumeClaim:
            claimName: deluge-pvc-downloads
        - name: deluge-completed
          persistentVolumeClaim:
            claimName: deluge-pvc-completed