apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin-svc
  namespace: jellyfin-ns
spec:
  type: LoadBalancer      
  ports:
    - name: "8096"
      port: 8096
      targetPort: 8096
  selector:
    app: jellyfin