apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-igr
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin-svc
            port:
              number: 9096