apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-igr
  namespace: jellyfin-ns
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: popcorn-iacono-io-tls
      hosts:
        - popcorn.iacono.io
  ingressClassName: traefik
  rules:
  - host: popcorn.iacono.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin-svc
            port:
              number: 9096